apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: qjs
  namespace: qjs
spec:
  interval: 5m
  path: "./manifests/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: qjs-demo
