apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: qjs-demo
  namespace: qjs
spec:
  interval: 1m
  url: https://github.com/cnuber/qjs-demo
  ref:
    branch: main
  ignore: |
    .git/
    .github/
    .sops.yaml
    .gitlab-ci.yml
